### ISSUE TITLE
Migrating from v3.2.4 throws a build error with GraphClient.builder() 

### ISSUE THREAD

**Issue by v-ken** [Shopify/mobile-buy-sdk-android#715]
Hi,

I'm having difficulty migrating from v3.2.4 to a newer version of this package.
The error I'm getting is `cannot find symbol` for the `builder` function in `GraphClient`.
This works fine in v3.2.4 and below.

```
/Users/development/app/android/app/src/main/java/com/ShopifyModule.java:229: error: cannot find symbol
      GraphClient graphClient = GraphClient.builder(this.context)
                                           ^
  symbol:   method builder(ReactApplicationContext)
  location: class GraphClient
```
